#!/usr/bin/env node
// build-data.mjs — github-pick data generator.
//
// Reads config.json + every sessions/*.json at the repo root and emits data.js,
// the single file the static dashboard (index.html) loads via <script src>.
// file:// pages cannot fetch() local files, so config + sessions must be
// inlined into a plain JS file at build time.
//
// Zero dependencies: only the Node built-ins below. Run with `node scripts/build-data.mjs`.

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

// --- Resolve the repo root from this file's location (not the cwd) -----------
// This file lives at <root>/scripts/build-data.mjs, so the root is the parent
// of the scripts/ directory. Resolving this way means the script works no
// matter where it is invoked from.
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(__dirname);

const CONFIG_PATH = join(ROOT, "config.json");
const SESSIONS_DIR = join(ROOT, "sessions");
const OUTPUT_PATH = join(ROOT, "data.js");

// lang defaults to null = "not chosen yet"; the AI agent asks on first run and
// writes it. The dashboard treats a null lang as a display-only zh fallback.
const DEFAULT_CONFIG = { lang: null, ui: null };

// Print a path relative to the repo root for tidy, copy-pasteable messages.
const rel = (p) => relative(ROOT, p);

// --- 1. Load config.json -----------------------------------------------------
// config.json is the source of truth for { lang, ui }. If it is missing or
// unparseable we fall back to the built-in default and warn (rather than crash),
// so a broken config never blocks regenerating the dashboard.
function loadConfig() {
  if (!existsSync(CONFIG_PATH)) {
    console.warn(`⚠ ${rel(CONFIG_PATH)} not found — using default config { lang: null, ui: null }.`);
    return { ...DEFAULT_CONFIG };
  }
  try {
    const parsed = JSON.parse(readFileSync(CONFIG_PATH, "utf8"));
    // Normalise: keep only the contract keys, backfill any that are absent.
    return {
      lang: typeof parsed.lang === "string" ? parsed.lang : DEFAULT_CONFIG.lang,
      ui: parsed.ui ?? null,
    };
  } catch (err) {
    console.warn(`⚠ ${rel(CONFIG_PATH)} is unparseable (${err.message}) — using default config.`);
    return { ...DEFAULT_CONFIG };
  }
}

// --- 2. Load every sessions/*.json -------------------------------------------
// Each file holds exactly one session object. A parse error here is fatal: we
// print the offending file + message and exit non-zero so the agent/user sees
// precisely which session broke (e.g. an ASCII double-quote inside a CJK string).
function loadSessions() {
  if (!existsSync(SESSIONS_DIR)) {
    console.warn(`⚠ ${rel(SESSIONS_DIR)}/ not found — no sessions to build.`);
    return [];
  }

  const files = readdirSync(SESSIONS_DIR)
    .filter((name) => name.endsWith(".json"))
    .sort();

  const sessions = [];
  for (const name of files) {
    const filePath = join(SESSIONS_DIR, name);
    let session;
    try {
      session = JSON.parse(readFileSync(filePath, "utf8"));
    } catch (err) {
      // Clear, machine-grep-able failure line, then bail out.
      console.error(`✖ ${rel(filePath)}: ${err.message}`);
      process.exit(1);
    }
    sessions.push(session);
  }
  return sessions;
}

// --- 3. Sort: date DESC, then slug ASC ---------------------------------------
// Newest sessions first; ties broken by slug for a stable, deterministic order.
function sortSessions(sessions) {
  return sessions.sort((a, b) => {
    const dateA = a?.date ?? "";
    const dateB = b?.date ?? "";
    if (dateA !== dateB) return dateB.localeCompare(dateA); // DESC
    const slugA = a?.slug ?? "";
    const slugB = b?.slug ?? "";
    return slugA.localeCompare(slugB); // ASC
  });
}

// --- 4. Count projects (for the summary line) --------------------------------
// Tolerant of missing categories/projects arrays.
function countProjects(sessions) {
  let total = 0;
  for (const s of sessions) {
    for (const cat of s?.categories ?? []) {
      total += (cat?.projects ?? []).length;
    }
  }
  return total;
}

// --- main --------------------------------------------------------------------
const config = loadConfig();
const sessions = sortSessions(loadSessions());

// Compose data.js with the exact three-part shape the dashboard expects:
//   line 1: generator banner
//   line 2: CONFIG — compact, single line
//   then:   SESSIONS — pretty-printed with 2-space indent
const output =
  "// auto-generated by github-pick — do not edit by hand\n" +
  `const CONFIG = ${JSON.stringify(config)};\n` +
  `const SESSIONS = ${JSON.stringify(sessions, null, 2)};\n`;

writeFileSync(OUTPUT_PATH, output, "utf8");

// --- 5. One-line success summary ---------------------------------------------
const projectCount = countProjects(sessions);
console.log(
  `✔ ${rel(OUTPUT_PATH)} — ${sessions.length} session(s), ${projectCount} project(s), lang "${config.lang || "(unset — chosen on first run)"}".`
);
